sensor:
  - platform: template
    sensors:
      # Find latest strike
      latest_lightning_strike_entity_id:
        friendly_name: "Latest Lightning Strike Entity ID"
        value_template: >
          {% set strikes = states.geo_location | selectattr('entity_id', 'search', 'geo_location.lightning_strike_') | sort(attribute='last_updated', reverse=true) | list %}
          {{ strikes[0].entity_id if strikes else 'none' }}
      
      # Extract latitude from the latest strike
      latest_lightning_strike_latitude:
        friendly_name: "Latest Lightning Strike Latitude"
        value_template: >
          {% set id = states('sensor.latest_lightning_strike_entity_id') %}
          {% if id != 'none' %}
            {{ states[id].attributes.latitude }}
          {% else %}
            unknown
          {% endif %}
      
      # Extract longitude from the latest strike
      latest_lightning_strike_longitude:
        friendly_name: "Latest Lightning Strike Longitude"
        value_template: >
          {% set id = states('sensor.latest_lightning_strike_entity_id') %}
          {% if id != 'none' %}
            {{ states[id].attributes.longitude }}
          {% else %}
            unknown
          {% endif %}

  # Get real location names from coordinates
  - platform: rest
    name: Latest Lightning Strike Area
    resource_template: >-
      https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat={{ states('sensor.latest_lightning_strike_latitude') }}&lon={{ states('sensor.latest_lightning_strike_longitude') }}
    headers:
      User-Agent: HomeAssistant/1.0
    value_template: >
      {{ value_json.address.suburb
         or value_json.address.city
         or value_json.address.town
         or value_json.address.village
         or value_json.address.state
         or value_json.display_name }}
    scan_interval: 3600
    
input_number:
  # Track previously notified strike distance
  lightning_last_distance:
      name: Last Lightning Distance
      initial: 1000
      min: 0
      max: 1000
      step: 0.1
      unit_of_measurement: "km"
      mode: box
