blueprint:
  name: Blitz-LightningTracker
  description: |
    Send a notification with map when lightning strikes within a specified distance.
    Designed specifically for the Blitzortung Lightning Detector integration.
    Includes strike location, direction, and interactive map view.
    Automatically uses your system's configured units (km or miles).
  domain: automation
  source_url: https://github.com/zacharyd3/Blitz-LightningTracker/blob/main/lightning_tracker.yaml
  input:
    notification_title:
      name: Notification Title
      description: Title for the notification
      default: "Lightning Strike Nearby!"
      selector:
        text:
    max_distance:
      name: Maximum Distance (km)
      description: Maximum distance in kilometers to trigger notification
      default: 7.5
      selector:
        number:
          min: 1
          max: 50
          step: 0.25
          unit_of_measurement: km
    lightning_distance_sensor:
      name: Lightning Distance Sensor
      description: Blitzortung distance sensor (usually ends with '_distance')
      selector:
        entity:
          integration: blitzortung
    lightning_azimuth_sensor:
      name: Lightning Azimuth Sensor  
      description: Blitzortung azimuth/direction sensor (usually ends with '_azimuth')
      selector:
        entity:
          integration: blitzortung
    notify_device:
      name: Mobile Device
      description: Select a phone or tablet with the mobile app installed
      selector:
        device:
          integration: mobile_app
    advanced:
      name: Additional options
      icon: mdi:cog
      description: Configure optional Features
      collapsed: true
      input:
        notification_channel:
          name: Notification Channel
          description: Notification channel for Android's notification system
          default: ""
          selector:
            text:
              type: text
        notification_timeout:
          name: Notification Timeout (minutes)
          description: Time before Android automatically clears the notification
          default: 10
          selector:
            number:
              min: 1
              max: 120
              step: 1
              unit_of_measurement: minutes
        google_maps_api_key:
          name: Google Maps API Key
          description: |
            Your Google Maps Static API key for map images.
            Get one at: https://console.cloud.google.com/apis/credentials
            Leave empty to disable map images.
          default: ""
          selector:
            text:
              type: password
        include_map_image:
          name: Include Map Image
          description: Include a static map image in the notification (requires API key)
          default: false
          selector:
            boolean:
        show_device_location:
          name: Show Device Location on Map
          description: Show your device's location as a blue pin on the map image
          default: true
          selector:
            boolean:
        only_notify_closer_strikes:
          name: Only Notify for Closer Strikes
          description: Only send notifications when lightning strikes are getting closer than the last notification
          default: false
          selector:
            boolean:
        cooldown_minutes:
          name: Cooldown Period (minutes)
          description: Minimum time between notifications to avoid spam. The minimum is 0.5 min. due to trying to keep within the rate limit of openstreetmaps.
          default: 1.5
          selector:
            number:
              min: 0.5
              max: 10
              step: 0.5
              unit_of_measurement: minutes
        

alias: "⚡ Lightning Nearby - Blitz-LightningTracker"
description: "Notify if lightning strikes within specified distance"
use_blueprint:
  path: lightning_notification.yaml

triggers:
  - entity_id: !input lightning_distance_sensor
    below: !input max_distance
    trigger: numeric_state

variables:
  input_only_notify_closer_strikes: !input only_notify_closer_strikes
  input_lightning_distance_sensor: !input lightning_distance_sensor

conditions:
  

actions:
  - condition: template
    value_template: |
      {%- if not input_only_notify_closer_strikes -%}
        true
      {%- else -%}
        {%- set current_distance = states(input_lightning_distance_sensor) | float -%}
        {%- set last_distance = states('input_number.lightning_last_distance') | float(999) -%}
        {{ current_distance < last_distance }}
      {%- endif -%}
  # Setup base variables (also nice for troubleshooting)
  - variables:
      input_lightning_distance_sensor: !input lightning_distance_sensor
      input_lightning_distance: "{{ states(input_lightning_distance_sensor) }}"
      raw_device: !input notify_device
      input_notify_device: "{{ 'notify.mobile_app_' ~ (device_attr(raw_device, 'name') | string | lower | replace(' ', '_') | replace(\"'\", '') | replace(\"'\", '') | replace('`', '') | replace('\"', '') | trim) }}"
      device_tracker_entity: "{{ device_entities(raw_device) | select('match', 'device_tracker') | first }}"
      device_latitude: "{{ state_attr(device_tracker_entity, 'latitude') }}"
      device_longitude: "{{ state_attr(device_tracker_entity, 'longitude') }}"
      input_notification_title: !input notification_title
      input_notification_channel: !input notification_channel
      input_notification_timeout: !input notification_timeout
      input_google_maps_api_key: !input google_maps_api_key
      input_include_map_image: !input include_map_image
      input_show_device_location: !input show_device_location
      input_only_notify_closer_strikes: !input only_notify_closer_strikes
      # Get the correct unit from the distance sensor
      distance_unit: "{{ state_attr(input_lightning_distance_sensor, 'unit_of_measurement') | default('km') }}"

  # Update the strike area sensor
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id: sensor.latest_lightning_strike_area

  # Send the notification
  - action: '{{ input_notify_device }}'
    data:
      title: '{{ input_notification_title }}'
      message: >
        Strike detected {{ input_lightning_distance }} {{ distance_unit }} away in {{
        states('sensor.latest_lightning_strike_area') }}.
      data:
        notification_icon: mdi:flash
        channel: "{{ input_notification_channel }}"
        timeout: "{{ input_notification_timeout * 60 | int }}"
        ttl: 0
        priority: high
        clickAction: >-
          https://maps.google.com/?q={{ state_attr(states('sensor.latest_lightning_strike_entity_id'), 'latitude') }},{{ state_attr(states('sensor.latest_lightning_strike_entity_id'), 'longitude') }}
        image: >
          {%- if input_include_map_image and input_google_maps_api_key != "" -%}
          https://maps.googleapis.com/maps/api/staticmap?zoom=auto&size=400x200&markers=color:yellow%7Csize:mid%7C{{ state_attr(states('sensor.latest_lightning_strike_entity_id'), 'latitude') }},{{ state_attr(states('sensor.latest_lightning_strike_entity_id'), 'longitude') }}
          {%- if input_show_device_location -%}
          &markers=color:blue%7Csize:mid%7C{{ device_latitude }},{{ device_longitude }}
          {%- endif -%}
          &key={{ input_google_maps_api_key }}
          {%- endif -%}

  # Store the current distance for next comparison
  - service: input_number.set_value
    data:
      entity_id: input_number.lightning_last_distance
      value: "{{ input_lightning_distance | float }}"
  
  - delay:
      minutes: !input cooldown_minutes

mode: single
